Equivalence relation
dafny-lang/libraries pull request #105
Opened 2023-03-06 16:42 UTC by stefan-aws

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2023-03-06 17:48 UTC, davidcok requested changes
Be sure to add some examples that serve as tests.

2023-03-06 17:48 UTC, davidcok commented on examples/Relations.dfy
> +    requires n > 1
Why not allow 1?

2023-03-06 17:55 UTC, stefan-aws commented on examples/Relations.dfy
> +    requires n > 1
Fixed

2023-03-07 13:23 UTC, jtristan approved these changes

2023-03-10 15:58 UTC, davidcok approved these changes
Since John has already approved, I'll add an approval.
But please add this change in src/dafny also -- and make any future changes there.

2023-03-10 15:58 UTC, merged