Extract element from singleton set
dafny-lang/libraries pull request #110
Opened 2023-03-10 15:10 UTC by stefan-aws

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2023-03-10 16:04 UTC, davidcok requested changes
Should have  an example that uses it -- in particular one that shows why this method should be used over simply `x :| x in s`

2023-03-21 18:05 UTC, stefan-aws commented on src/Collections/Sets/Sets.dfy
> +  method ExtractFromSingleton<T>(s: set<T>) returns (x: T)
Changed it to `function` and added context

2023-03-28 21:40 UTC, atomb approved these changes

2023-03-28 21:40 UTC, atomb commented on src/Collections/Sets/Sets.dfy
What's the long-term plan for these parallel trees? It seems like they'll be hard to maintain.

2023-03-28 21:40 UTC, merged

2023-03-28 21:45 UTC, stefan-aws commented on src/Collections/Sets/Sets.dfy
My understanding is that as we move forward, new code to the library should only be added to the `dafny` subfolder.