Fixed duplicate style guides and incorrect indentations
dafny-lang/libraries pull request #45
Opened 2022-07-19 17:22 UTC by davidcok

Merged styleguide with the one in the main project; made indentations 2 spaces

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2022-07-19 18:01 UTC, MikaelMayer requested changes

2022-07-19 18:01 UTC, MikaelMayer commented on STYLE.md
> +been compbined with the project style guide to avoid duplication and divergence.)
```suggestion
been combined with the project style guide to avoid duplication and divergence.)
```

2022-07-19 18:47 UTC, MikaelMayer approved these changes

2022-07-22 21:50 UTC, robin-aws reviewed
Looks like the only material change between this version and the core one is dropping the "lemmas should start with 'Lemma'" rule.

I'm in support of this, as the IDE is now highlighting all ghost operations/state explicitly, which makes this idiom much less necessary.

@parno any objections here?

2022-07-22 21:51 UTC, RustanLeino approved these changes

2022-07-22 21:52 UTC, merged

2022-07-23 00:40 UTC, parno commented
Seems like a reasonable change to me, but if that rule is being removed, should all of the existing lemmas in the library have their `Lemma` prefix removed?