converting set to sorted sequence
dafny-lang/libraries pull request #66
Opened 2023-01-20 17:31 UTC by stefan-aws

Adding support for set to ordered sequence conversion, as proposed by @cpitclaudel in https://github.com/dafny-lang/libraries/issues/59. I changed some of his initial notation.

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2023-01-20 17:55 UTC, davidcok commented
Suggestion: Mark this module as function-syntax 4 and use Dafny4 syntax, so the text does not need to be changed later.

2023-01-24 18:33 UTC, atomb submitted a review, later dismissed
This looks nice. One optional change I might make, but that's totally a matter of taste, would be to rename `GhostSetToSeq` to `SetToSeqSpec`.

2023-01-26 16:03 UTC, atomb approved these changes

2023-01-26 17:04 UTC, MikaelMayer requested changes
Great addition, two minor comments

2023-01-26 17:04 UTC, MikaelMayer commented on src/Collections/Sequences/Seq.dfy
> +     same multiset are equal. */
```suggestion
  /* Proves that any two sequences that are sorted by a total order and that have the same elements are equal. */
```

2023-01-26 17:04 UTC, MikaelMayer commented on src/Collections/Sequences/Seq.dfy
> +  /* Converts a set to sequence that is ordered w.r.t. a given total order. */
```suggestion
  /* Converts a set to a sequence that is ordered w.r.t. a given total order. */
```

2023-01-26 17:08 UTC, MikaelMayer approved these changes
Great job !

2023-01-26 17:28 UTC, atomb approved these changes

2023-01-26 17:45 UTC, merged